### ISSUE TITLE
Site is down?

### ISSUE THREAD

**Issue by tcaudilllg** [bjorn/rpgdx#1]
Can I get a copy?

**Comment by bjorn** [comment]
I recently noticed the site is down as well, but this is unintentional. I need to find some time to look into what made it fail. I think it's likely due to some software update on the host, since I didn't change anything myself.

**Comment by bjorn** [comment]
The statistics show me the site has already been down about 4 weeks. :-(

**Comment by bjorn** [comment]
Error is:

```
.htaccess: Invalid command 'order', perhaps misspelled or defined by a module not included in the server configuration
```

I guess this [Order Directive](https://httpd.apache.org/docs/2.2/mod/mod_authz_host.html#order) was deprecated and eventually removed. RPGDX currently runs on Apache 2.4, and may be doing so since 4 weeks.

**Comment by bjorn** [comment]
So, the main problem was fixed. Then, there were also some warnings about `ob_gzhandler` conflicting with `zlib.output_compression`, so I just turned off the latter for now. Though actually I still see there errors much of the time. I'll probably want to enable this option and turn off the gzip compression of the phpBB instead, but that brings me to another problem.

There are some encoding issues that make my name show up as "Bj�rn", and which are likely also related to the problem that I am unable to log in. This means that so far I have not been able to disable the gzip compression option of the forum itself...

Oh, and while the forum mostly works, the main site often looks like garbage, but not always when refreshing. It's probably also related to the compression issue.

**Comment by bjorn** [comment]
I've opened #2 and #3 about the other issues.

**Comment by bjorn** [comment]
@tcaudilllg Btw, to get to your question about whether you can get a copy, unfortunately that's a complicated issue. I've been asked the same thing by @RichardMarks. But how to decide who can have this data? What about all the private messages people may have sent to each other? What about IP addresses, e-mail addresses and passwords, even if hashed?

Maybe something to bring up on the forums... I have no idea about such things.
