### ISSUE TITLE
Forum post contents is empty

### ISSUE THREAD

**Issue by bjorn** [bjorn/rpgdx#10]
See for example https://rpgdx.net/forums/viewtopic.php?t=2831, but all topics appear to be affected.

The posts are there with all their meta-info, but the contents are missing.

**Comment by bjorn** [comment]
This is due to the "bad words" filter (in practice, this is only used on RPGDX to correct spelling errors). Probably changes in PHP have caused the existing expressions to filter out the post content's entirely.

Since I'm not sure how to fix this, I have just commented out the filter for now.

**Comment by Poikilos** [comment]
The ereg shim may make too many assumptions and need to be improved. It is the same code as upstream other than the structure (I just made it not require composer), but I can look at the code again and make sure I didn't remove any functionality, and also improve the upstream functionality if necessary.

**Comment by bjorn** [comment]
@Poikilos Would be nice if you could look into it. I've opened #17 about it, now that this issue is closed.
