### ISSUE TITLE
auto_prepend_file setting is not working on the live server

### ISSUE THREAD

**Issue by Poikilos** [bjorn/rpgdx#14]
> I could not get the auto_prepend_file setting to work, so instead I've included the shims in forums/common.php. This is of course another annoying local change.

-@bjorn (https://github.com/bjorn/rpgdx/pull/9#issuecomment-2125645067)

**Comment by Poikilos** [comment]
Maybe check and make sure the owner of the file is the www user if the www user is a specific low-priv user on your server.

**Comment by Poikilos** [comment]
Also make sure it is the right php.ini. A special configuration can cause a different php.ini to be used. Try making a:

which-ini.php
```PHP
<?php
$inipath = php_ini_loaded_file();
if ($inipath) {
    echo 'Loaded php.ini: ' . $inipath;
} else {
    echo 'A php.ini file is not loaded';
}
?>
```
-from https://stackoverflow.com/questions/14558150/how-can-i-know-which-php-ini-file-is-used

and remember to delete the file later

One more thing... Remember, there can only be one `auto_prepend_file` line, so if there is another one later (possibly php.d/ ones run later?), it will override the previous line.

**Comment by bjorn** [comment]
Turned out my change to the `php.ini` was just not taking effect yet... The site is hosted by NearlyFreeSpeech and I needed to execute `nfsn web-kick` for the change to go live.
