### ISSUE TITLE
Document whether the "contrib" folder from phpBB is necessary

### ISSUE THREAD

**Issue by Poikilos** [bjorn/rpgdx#8]
During install of phpBB on a fresh server, typically both the contrib and install folders are present. I included the install folder in my branch since that needed to be edited, but it is unclear whether the contrib folder (from phpBB 2.0.23) would be necessary in a fresh install.

**Comment by bjorn** [comment]
I don't see a `contrib` folder in the live setup nor in the repository, so I don't think we've ever used anything from that directory.

**Comment by bjorn** [comment]
When I had the install folder still around, the forum was telling me that both the `install` and the `contrib` folders needed to be deleted, so I guess this is likely already part of phpBB docs somewhere. I also read that phpBB 3 no longer has a "contrib" folder, anyway.
